### 회원가입
POST localhost:3000/users
Content-Type: application/json

{
  "name": "우태현",
  "email": "wth2052@gmail.com",
  "password": "dkssudgktpdygg"
}

### 이메일
//curl -X POST http://127.0.0.1:3000/users/email-verify\?signupVerifyToken\=test_token
POST localhost:3000/users/email-verify
Content-Type: application/json

{
  "signupVerifyToken": "test_token"
}

### 로그인
POST localhost:3000/users/login
Content-Type: application/json

{
  "email": "wth2052@gmail.com",
  "password": "dkssudgktpdygg"
}

### 회원 정보 조회
GET localhost:3000/users/01GSSVG744SM7S24ZS8SP72TD4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxR1NTVkc3NDRTTTdTMjRaUzhTUDcyVEQ0IiwibmFtZSI6IuyasO2DnO2YhCIsImVtYWlsIjoid3RoMjA1MkBnbWFpbC5jb20iLCJpYXQiOjE2NzY5Nzg3MDcsImV4cCI6MTY3NzA2NTEwNywiYXVkIjoiZXhhbXBsZS5jb20iLCJpc3MiOiJleGFtcGxlLmNvbSJ9.Le-77a8dS8lVdDti8c3SsQ4qsce3vvf9MvpZI_eeEDA

### 메일 인증
POST localhost:3000/users/
Content-Type: application/json

{
  "name": "우태현",
  "email": "wth2052@gmail.com",
  "password": "dkssudgktpdygg"
}

### Health-Check
GET http://localhost:3000/health-check
Content-Type: application/json