POST 172.18.142.38:3000/users
Content-Type: application/json

{
  "name": "dnxogus",
  "email": "wth2052@gmail.com",
  "password": "password1234"
}

###
POST http://172.18.142.38:3000/users/email-verify\?signupVerifyToken\=test_token
Content-Type: application/json

{
  "signupVerifyToken" : "test_token"
}


### 로그인

POST http://172.18.142.38:3000/users/login
Content-Type: application/json

{
  "email": "wth2052@gmail.com",
  "password": "password1234"
}

### 회원 정보 조회
GET http://172.18.142.38:3000/users/01GSPS2F6TWDAZP70XMV217SRG
Content-Type: application/json

{
  "id": "01GSPS2F6TWDAZP70XMV217SRG",
  "name": "dnxogus",
  "email": "wth2052@gmail.com"
}
### 메일 인증
POST http://172.18.142.38:3000/users
Content-Type: application/json

{
  "name": "wth123",
  "email": "wth2052@gmail.com",
  "password": "dnxogus123123"
}

### 헬스 체크
GET http://127.0.0.1:3000/health-check

